# Generated by Django 2.2.1 on 2019-05-16 17:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=30)),
                ('ptr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('council', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('enrolment', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('ptr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('enrolment', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('ptr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileCvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('uploadcvs', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('status_update', models.IntegerField(default=0)),
                ('length', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(12)])),
                ('cv', models.FileField(upload_to='CVs/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
