# Generated by Django 2.2.1 on 2019-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='home_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
