# Generated by Django 2.2.1 on 2019-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0002_auto_20190516_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
