# Generated by Django 2.2.1 on 2019-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0003_auto_20190516_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
