# Generated by Django 2.2.1 on 2019-06-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0005_auto_20190613_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
