# Generated by Django 2.2.1 on 2019-06-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0007_volunteer_professional_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='professional_summary',
            new_name='carrier',
        ),
    ]
