# Generated by Django 2.2.1 on 2019-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0008_auto_20190613_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='experience',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='why_volunteer',
            field=models.TextField(default=32),
            preserve_default=False,
        ),
    ]
