# Generated by Django 2.2.1 on 2019-06-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0009_auto_20190613_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='username',
        ),
    ]
