# Generated by Django 2.2.1 on 2019-07-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0011_auto_20190613_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='certificate',
            field=models.CharField(choices=[('Certificate level', 'Certificate level'), ('Diploma level', 'Diploma level'), ('Degree level', 'Degree level'), ('Masters level', 'Masters level')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
