# Generated by Django 2.2.1 on 2019-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0013_remove_volunteer_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
